# Generated by Django 5.0.6 on 2024-07-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название кура')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('imagery', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение(превью)')),
            ],
            options={
                'verbose_name': 'Учебный курс',
                'verbose_name_plural': 'Учебные курсы',
            },
        ),
    ]
