# Generated by Django 5.0.6 on 2024-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcourse',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название курса'),
        ),
    ]
