# Generated by Django 5.0.6 on 2024-07-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_learningcourse_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
